name: "FFmpeg Timelapse"

on:
  push:
  workflow_dispatch:

jobs:
  timelapse:
    runs-on: ubuntu-latest
    name: Timelapse
    steps:
      - uses: actions/checkout@v3
      - run: echo "name=date::$(date +'%Y%m%d')"
        id: date
      - run: echo "name=jpgs::$(ls)"
        id: jpgs
      - uses: FedericoCarboni/setup-ffmpeg@v1
        id: setup-ffmpeg
      - run: ffmpeg -framerate 18 -i -1001404797626-6162-%03d.jpg -c:v libx264 -crf 28 -vf scale=2028:-1 -an timelapse.mp4
      - name: Expose generated video as artifact
        uses: actions/upload-artifact@v2
        with:
          name: Timelapse
          path: timelapse.mp4
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: timelapse.mp4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
